import { withVectorIcon } from '../withIcon';
import CircleSVG from './circle.svg?react';
import CircleFilledSVG from './circle_filled.svg?react';
import GroupFilledSVG from './group_filled.svg?react';
import LinkSVG from './link.svg?react';
import MoonFilledSVG from './moon_filled.svg?react';
import MoonSVG from './moon.svg?react';
import PersonFilledSVG from './person_filled.svg?react';
import SunFilledSVG from './sun_filled.svg?react';
import SunSVG from './sun.svg?react';

export const CircleIcon = withVectorIcon(CircleSVG);
export const CircleFilledIcon = withVectorIcon(CircleFilledSVG);
export const GroupFilledIcon = withVectorIcon(GroupFilledSVG);
export const LinkIcon = withVectorIcon(LinkSVG);
export const MoonFilledIcon = withVectorIcon(MoonFilledSVG);
export const MoonIcon = withVectorIcon(MoonSVG);
export const PersonFilledIcon = withVectorIcon(PersonFilledSVG);
export const SunFilledIcon = withVectorIcon(SunFilledSVG);
export const SunIcon = withVectorIcon(SunSVG);